---
title: "p-value test"
author: "Rebecca"
format: html
editor: visual
---

```{r}
library("tidyverse")
```

```{r}
data_path <- here("data/06_dat_augmented.csv")
dataset <- read_csv(data_path, show_col_types = FALSE)
dataset
```

```{r}
dataset <- dataset |> 
  filter(!glucose_tollerance == "impaired") |> 
  mutate( glucose_tollerance_p= case_when(glucose_tollerance == "normal" ~ 0,
                       glucose_tollerance == "t2d" ~ 1))
```

```{r}
dataset_subsection_long <- dataset |> 
  select(-all_of(starts_with("s_"))) |> 
  select(-sampleID,-statins,-insulin,-country,-BMI_class) |>
  pivot_longer(cols = !starts_with("gl"),
               names_to = "data_point",
               values_to = "value")
dataset_subsection_long  
```

```{r}
dataset_subsection_long_nested <- dataset_subsection_long |>
  group_by(data_point) |> 
  nest() |> 
  ungroup()
```

```{r}
dataset_subsection_aug_long_nested <- dataset_subsection_long_nested |> 
  group_by(data_point) |> 
  mutate(model_object = map(.x = data,
                   .f = ~lm(formula = value ~ glucose_tollerance_p,
                            data = .x))) |> 
  mutate(model_object_tidy = map(.x = model_object,
                                 .f = ~tidy(x = .x,
                                            conf.int = TRUE,
                                            conf.level = 0.95)))
  
dataset_subsection_aug_long_nested
```

```{r}
dataset_subsection_aug_long_nested |> 
  filter(data_point == "bmi") |> 
  pull(model_object_tidy)
```

```{r}
dataset_subsection_estimates <- dataset_subsection_aug_long_nested |> 
  unnest(model_object_tidy)
dataset_subsection_estimates
```

```{r}
dataset_subsection_estimates <- dataset_subsection_estimates |> 
  filter(term == "glucose_tollerance_p") |> 
  select(data_point, p.value, estimate, conf.low, conf.high) |> 
  ungroup()
dataset_subsection_estimates
```

```{r}
dataset_subsection_estimates <- dataset_subsection_estimates |>
  mutate(q.value = p.adjust(p.value),
         is_significant = case_when(q.value <= 0.05 ~ "yes",
                                    q.value > 0.05 ~ "no"))
dataset_subsection_estimates |> 
  filter(is_significant == "yes")
```

```{r}
dataset_subsection_estimates |> 
  filter(is_significant == "yes") |> 
  ggplot(aes(x = estimate,
             y = fct_reorder(data_point, estimate),
             xmin = conf.low,
             xmax = conf.high)) +
  geom_vline(xintercept = 0) +
  geom_errorbarh() +
  geom_point() +
  theme_minimal(base_size = 10) +
  theme(plot.title = element_text(hjust = 1)) +
  labs(x = "Estimates (95%CIs)",
       y = "",
       title = "perammeteres Associated with t2d")
```
