```{r}
library("tidyverse")
library("here")
data_path<-here("data/06_dat_augmented.csv")
datset<- read_csv(data_path,show_col_types=FALSE)

```

```{r}
microbe_dataset<-dataset|>
  select(starts_with("s"),sampleID)|>
  mutate(across(everything(),~ifelse(is.numeric(.)&.==0,0.0000001,.)))|>
  group_by(sampleID)
view(microbe_dataset)
```

```{r}
bacteria_mean<- species_dataset|>
rowwise() |>
  mutate(mean = mean(c_across(where(~ is.numeric(.))))) |>
 ungroup() |>
 relocate(mean,.after=sampleID)

 

bacteria_log<- bacteria_mean|>
 select-c(sampleID,mean,statins)|>
rowwise() |>
mutate(across(everything(), ~ log2(. / mean(c_across(everything())))))|>
ungroup() 


 
#PCA analysis of species

pca_clr <- prcomp(bacteria_log |> select(-c(sampleID,mean,statins)), center = TRUE, scale. = FALSE)
 
pca_data_clr <- as.data.frame(pca_clr$x)
summary(pca_clr)

 
ggplot(pca_data_clr, aes(x = PC1, y = PC2)) +
 geom_point(alpha = 0.6) +
 labs(title = "PCA of CLR-transformed species data", x = "PC1", y = "PC2") +
  theme_minimal()

```

```{r}
proportion_variance<- pca_clr$sdev^2/sum(pca_clr$sdev^2)
percentage_variance<- proportion_variance*100
barplot(percentage_variance,main = "square componants",xlab="principal componant",ylab="percent variation")
#pc1 accounts for the most variance ,so we consider it 
results<- pca_clr$rotation[,1]
species_score<-abs(results)
species_score
species_score_ranked<-species_score|>
as_tibble(rownames="species")|>
  arrange(desc(value))|>
  slice_head(n=10)

```

Now we visualize these species across the different gropus 













